mkdir ~/labirintoa
mkdir -p ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/.15gela/Zorionak
touch ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/.15gela/Zorionak/klabea
echo "E2qdtJ" >> ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/.15gela/Zorionak/klabea
touch ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/boooooooo
echo " .-.\n(o o)   Booooo, preso geratu nintzen erronkariaren\n| O \   mamua naiz. Pista batekin lagunduko dizuet:\n \   \  'ls' erabili beharrean, erabili 'ls -a'.\n  '~~~' Labirintoaren sekretua ikusiko duzu." >>  ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/boooooooo
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/.15gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/ezkerrera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/.14gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela/behera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/.13gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/ezkerrera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/.12gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/gora
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/.11gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/gora
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/.10gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/gora
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/.9gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/eskubira
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/.8gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela/behera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/.7gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/ezkerrera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/.6gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela/behera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela/.5gela ~/labirintoa/.1gela/.2gela/.3gela/.4gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/.4gela/behera
ln -s ~/labirintoa/.1gela/.2gela/.3gela/.4gela ~/labirintoa/.1gela/.2gela/.3gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/.3gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/eskubira
ln -s ~/labirintoa ~/labirintoa/.1gela/.2gela/gora
ln -s ~/labirintoa/.1gela/.2gela/.3gela ~/labirintoa/.1gela/.2gela/behera
ln -s ~/labirintoa ~/labirintoa/.1gela/ezkerrera
ln -s ~/labirintoa ~/labirintoa/.1gela/eskubira
ln -s ~/labirintoa/.1gela/.2gela ~/labirintoa/.1gela/gora
ln -s ~/labirintoa ~/labirintoa/.1gela/behera
ln -s ~/labirintoa ~/labirintoa/ezkerrera
ln -s ~/labirintoa ~/labirintoa/eskubira
ln -s ~/labirintoa/.1gela ~/labirintoa/gora
ln -s ~/labirintoa ~/labirintoa/behera
echo "Labirintoa sortu da!"
